package:
  name: xbrainmap
  version: '0.1.0'

source:
  git_url: https://github.com/xbrainmap/xbrainmap.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - xbrainmap
    - xbrainmap.mosaic
    - xbrainmap.segment
    - xbrainmap.tomo

about:
  home: http://xbrainmap.rtfd.org
  license: BSD-3
  summary: 'Brain mapping with x-rays.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
